version: "3"
services: 
    server:
        image: docker.bitnp.net/bitnp/live/danmu:latest
        restart: always
        ports:
            - 8888:8888
    fluentd:
        image: fluentd
        restart: always
    mongo:
        image: mongo
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: fluentd
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment: 
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
