version: "3"
services: 
    server:
        image: docker.bitnp.net/bitnp/live/danmu/server:master
        restart: always
        ports:
            - 8888:8888

    fluentd:
        image: docker.bitnp.net/bitnp/live/danmu/fluentd:master
        restart: always

    mongo:
        image: docker.bitnp.net/bitnp/live/danmu/mongo:master
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: fluentd

    mongo-express:
        image: docker.bitnp.net/bitnp/live/danmu/mongo-express:master
        restart: always
        ports:
            - 8081:8081
        environment: 
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
